development:
   #-- -- -- -- -- --
   adapter: sqlserver
   mode: dblib
   dataserver: 200.67.149.236
   database: metas_ensb_development
   username: sa
   password: C0r10ll15
   timeout: 5000
  #-- -- -- -- --
  #host: localhost
  #adapter: mysql2
  #database: sis_ensb_development
  #username: root
  #password: idefix
  # -- -- -- -- --

  #adapter: postgresql
  #encoding: unicode
  #database: sis_ensb_development
  #pool: 5
  #username: postgres
  #password: idefix
  #host: localhost
  #port: 5432
test:
  adapter: sqlserver
  mode: dblib
  dataserver: 200.67.149.236
  database: metas_ensb_test
  username: sa
  password: C0r10ll15
  timeout: 5000

production:
  adapter: sqlserver
  mode: dblib
  dataserver: 200.67.149.236
  database: metas_ensb_production
  username: sa
  password: C0r10ll15
  timeout: 5000